# Generated by Django 3.0.8 on 2020-08-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_inpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Inpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
    ]
