# Generated by Django 3.0.8 on 2020-08-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_food_inpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_Inpo',
        ),
    ]
