# Generated by Django 3.0.8 on 2020-08-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_point',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
