<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-08-12 06:56
=======
# Generated by Django 2.0.13 on 2020-08-12 06:59
>>>>>>> d6fe0fd63566d1ec192b13f7548abb20632250bb

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_point_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_point',
            name='tel',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
