# Generated by Django 3.0.8 on 2020-08-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_point_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Inpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='food_point',
            name='location',
        ),
        migrations.RemoveField(
            model_name='food_point',
            name='tel',
        ),
    ]
